desactivar btn Anterior y Siguiente cuando id está fuera de rango
dlab-team/c19-frontend pull request #27
Opened 2024-06-15 09:12 UTC by Olozano1194

2024-06-20 19:40 UTC, memomr requested changes
existen errores para el deploy en netlify, favor corregir

2024-06-21 22:25 UTC, memomr approved these changes

2024-06-22 00:22 UTC, Needforock2 commented
@Olozano1194 parece que hay conflictos con la rama develop que recién @Francovc12 hizo merge, por fa revisalo con él para sacar los conflictos. Cualquier cosa me avisan para apoyarlos

2024-06-23 23:42 UTC, memomr requested changes
resolver conflictos con rama develop para poder hacer merge

2024-06-25 04:15 UTC, Olozano1194 commented
Buena noche, que pena la hora....acabo de solucionar los conflictos del componente advance...una pregunta debo de darle clic al btn de Merge pull request?....como veníamos haciendo desde un comienzo?

2024-06-25 14:43 UTC, memomr approved these changes

2024-06-25 14:45 UTC, merged